name: CI/CD Deployment

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Pull backend image
        run: docker pull ersurjeetkumar9389/institute-backend:latest

      - name: Pull frontend image
        run: docker pull ersurjeetkumar9389/institute-frontend:latest

      - name: Deploy containers
        run: |
          docker stop node_backend || true
          docker rm node_backend || true
          docker stop react_frontend || true
          docker rm react_frontend || true

          docker run -d --name node_backend \
            -e NODE_ENV=development \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e CLOUD_NAME="${{ secrets.CLOUD_NAME }}" \
            -e API_KEY="${{ secrets.API_KEY }}" \
            -e API_SECRET="${{ secrets.API_SECRET }}" \
            -e RAZORPAY_KEY="${{ secrets.RAZORPAY_KEY }}" \
            -e RAZORPAY_SECRET="${{ secrets.RAZORPAY_SECRET }}" \
            -e MAIL_HOST="${{ secrets.MAIL_HOST }}" \
            -e EMAIL_USER="${{ secrets.EMAIL_USER }}" \
            -e EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -p 5000:5000 \
            ersurjeetkumar9389/institute-backend:latest

          docker run -d --name react_frontend \
            -p 5173:80 \
            ersurjeetkumar9389/institute-frontend:latest
